ifdef::context[:parent-context: {context}]
[id="adding-a-readiness-health-check-procedure_{context}"]
= Adding a readiness health check procedure
:context: adding-a-readiness-health-check-procedure

In the previous section, we created a simple liveness health check procedure which states
whether our application is running or not. In this section, we will create a readiness
health check which will be able to state whether our application is able to process
requests.

We will create another health check procedure that simulates a connection to
an external service provider such as a database. For starters, we will always return
the response indicating the application is ready.

Create `org.acme.microprofile.health.DatabaseConnectionHealthCheck` class:

[source,java]
----
package org.acme.microprofile.health;

import org.eclipse.microprofile.health.HealthCheck;
import org.eclipse.microprofile.health.HealthCheckResponse;
import org.eclipse.microprofile.health.Readiness;

import javax.enterprise.context.ApplicationScoped;

@Readiness
@ApplicationScoped
public class DatabaseConnectionHealthCheck implements HealthCheck {

    @Override
    public HealthCheckResponse call() {
        return HealthCheckResponse.up("Database connection health check");
    }
}

----

If you now rerun the health check at `http://localhost:8080/health/live` the `checks`
array will contain only the previously defined `SimpleHealthCheck` as it is the only
check defined with the `@Liveness` qualifier. However, if you access
`http://localhost:8080/health/ready` (in the browser or with
`curl http://localhost:8080/health/ready`) you will see only the
`Database connection health check` as it is the only health check defined with the
`@Readiness` qualifier as the readiness health check procedure.

[NOTE,textlabel="Note",name="note"]
====
If you access `http://localhost:8080/health` you will get back both checks.
====

More information about which health check procedures should be used in which situation
is detailed in the MicroProfile Health specification. Generally, the liveness
procedures determine whether the application should be restarted while readiness
procedures determine whether it makes sense to contact the application with requests.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]