ifdef::context[:parent-context: {context}]
[id="bootstrapping-quarkus_{context}"]
= Bootstrapping Quarkus
:context: bootstrapping-quarkus

All Quarkus applications are created by the QuarkusBootstrap class in the `independent-projects/bootstrap` module. This
class is used to resolve all the relevant dependencies (both deployment and runtime) that are needed for the Quarkus
application. The end result of this process is a `CuratedApplication`, which contains all the class loading information
for the application.

The `CuratedApplication` can then be used to create an `AugmentAction` instance, which can create production application
and start/restart runtime ones. This application instance exists within an isolated ClassLoader, it is not necessary
to have any of the Quarkus deployment classes on the class path as the curate process will resolve them for you.

This bootstrap process should be the same no matter how Quarkus is launched, just with different parameters passed in.

include::modules/current-run-modes.adoc[leveloffset=+1]

include::modules/notes-on-transformer-safety.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]