ifdef::context[:parent-context: {context}]
[id="change-quarkus-http-port_{context}"]
= Change Quarkus HTTP Port
:context: change-quarkus-http-port

If you correctly followed the link:building-native-image[building native image guide], you should have a local container image named `quarkus-quickstart/getting-started`.

While Quarkus by default runs on port 8080, most Azure services expect web applications to be running on port 80. Before we continue, go back to your quickstart code and open the file `src/main/docker/Dockerfile.native`.

Change the last two commands in the `Dockerfile.native` file and make it read like this:

[source,docker]
----
EXPOSE 80
CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=80"]
----

Now you can rebuild the docker image:

[source,shell]
----
$ docker build -f src/main/docker/Dockerfile.native -t quarkus-quickstart/getting-started .
----

To test, run it by exposing port 80 into port 8080 in your host:

[source,shell]
----
$ docker run -i --rm -p 8080:80 quarkus-quickstart/getting-started
----

Your container image is now ready to run on Azure. Remember, the Quarkus application is mapped to run on port 80.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]