ifdef::context[:parent-context: {context}]
[id="datasource-metrics_{context}"]
= Datasource Metrics
:context: datasource-metrics

If you are using the `quarkus-smallrye-metrics` extension, `quarkus-agroal` can expose some data source metrics on the
`/metrics` endpoint. This can be turned on by setting the property `quarkus.datasource.metrics.enabled` to true.

For the exposed metrics to contain any actual values, it is necessary that metric collection is enabled internally
by Agroal mechanisms. By default, this metric collection mechanism gets turned on for all data sources if the `quarkus-smallrye-metrics`
is present and metrics for the Agroal extension are enabled. If you want to disable metrics for a particular data source,
this can be done by setting `quarkus.datasource.enable-metrics` to `false` (or `quarkus.datasource.<datasource name>.enable-metrics` for a named datasource). This disables
collecting the metrics as well as exposing them in the `/metrics` endpoint, because it does not make sense to
expose metrics if the mechanism to collect them is disabled.

Conversely, setting `quarkus.datasource.enable-metrics` to `true` (or `quarkus.datasource.<datasource name>.enable-metrics` for a named datasource) explicitly can be used to enable collection of metrics even if
the `quarkus-smallrye-metrics` extension is not in use. This can be useful if you need to access the collected metrics programmatically.
They are available after calling `dataSource.getMetrics()` on an injected `AgroalDataSource` instance. If collection of metrics is disabled
for this data source, all values will be zero.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]