ifdef::context[:parent-context: {context}]
[id="deploy-to-azure-container-instances_{context}"]
= Deploy to Azure Container Instances
:context: deploy-to-azure-container-instances

The simplest way to start this container in the cloud is with the Azure Container Instances service. It simply creates a container on Azure infrastructure.

There are different approaches for using ACI. Check the documentation for details. The quickest way to get a container up and running goes as it follows.

First step is to find the username and password for the admin, so that ACI can authenticate into ACR and pull the Docker image:

[source,shell]
----
$ az acr credential show --name <registry-name>
----

Now create the Docker instance on ACI pointing to your image on ACR:

[source,shell]
----
$ az container create \
    --name quarkus-hello \
    --resource-group <resource-group> \
    --image <acr-login-server>/quarkus-quickstart/getting-started \
    --registry-login-server <acr-login-server> \
    --registry-username <acr-username> \
    --registry-password <acr-password> \
    --dns-name-label quarkus-hello-<random-number> \
    --query ipAddress.fqdn
----

The command above, if run successfully, will give you the address of your container in the Cloud. Access your Quarkus application in the address displayed as output.

For more information and details on ACR authentication and the use of service principals, follow this guide below and remember the Azure Container Registry `loginServer` and the image name of your Quarkus application now hosted on the ACR.

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-using-azure-container-registry?WT.mc_id=opensource-quarkus-brborges[Deploy to Azure Container Instances from Azure Container Registry]

Keep in mind that this service does not provide scalability. A container instance is unique and does not scale.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]