ifdef::context[:parent-context: {context}]
[id="fetching-credentials-from-vault-with-hibernate-orm_{context}"]
= Fetching credentials from Vault with Hibernate ORM
:context: fetching-credentials-from-vault-with-hibernate-orm

Start a PostgreSQL database:

[source,shell]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 --name postgres-quarkus-hibernate -e POSTGRES_USER=sarah -e POSTGRES_PASSWORD=connor -e POSTGRES_DB=mydatabase -p 5432:5432 postgres:10.5
----

Create a simple service:

[source,java]
----
@ApplicationScoped
public class SantaClausService {

    @Inject
    EntityManager em;

    @Transactional
    public List<Gift> getGifts() {
        return (List<Gift>) em.createQuery("select g from Gift g").getResultList();
    }
}
----

With its `Gift` entity:

[source,java]
----
@Entity
public class Gift {

    private Long id;
    private String name;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="giftSeq")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
----

Finally, add a new endpoint in `GreetingResource`:

[source,java]
----
@Inject
SantaClausService santaClausService;

@GET
@Path("/gift-count")
@Produces(MediaType.TEXT_PLAIN)
public int geGiftCount() {
    return santaClausService.getGifts().size();
}
----

Create a new path in Vault where the database password will be added:

[source,shell,subs="attributes+"]
----
# set the root token again
export VAULT_TOKEN={root-token}
vault kv put secret/myapps/vault-quickstart/db password=connor
----

Since we allowed read access on `secret/myapps/vault-quickstart/` subpaths in the policy, there is nothing else
we have to do to allow the application to read it.

When fetching credentials from Vault that are intended to be used by the Agroal connection pool, we need
first to create a named Vault credentials provider in the {config-file}:

[source,properties]
----
quarkus.vault.credentials-provider.mydatabase.kv-path=myapps/vault-quickstart/db
----

This defines a credentials provider `mydatabase` that will fetch the password from key `password`
at path `myapps/vault-quickstart/db`.

The credentials provider can now be used in the datasource configuration, in place of the `password`
property:

[source,properties]
----
# configure your datasource
quarkus.datasource.url = jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver = org.postgresql.Driver
quarkus.datasource.username = sarah
#quarkus.datasource.password = connor
quarkus.datasource.credentials-provider = mydatabase

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
----

[NOTE,textlabel="Note",name="note"]
====
Another way to specify the datasource password is with property indirection. Assuming that vault path
`myapps/vault-quickstart/config` contains key `my-db-password`, all is required on the datasource configuration is:[source]
----
quarkus.datasource.username = sarah
quarkus.datasource.password = ${my-db-password}
----The only drawback is that the password will never be fetched again from vault after the initial property loading.
This means that if the db password was changed while running, the application would have to be restarted after
vault has been updated with the new password.
This contrasts with the credentials provider approach, which fetches the password from vault everytime a connection
creation is attempted.
====

Restart the application after rebuilding it, and test it with the new endpoint:

[source,shell]
----
curl http://localhost:8080/hello/gift-count
----

You should see:

[source,shell]
----
0
----

[NOTE,textlabel="Note",name="note"]
====
The Vault extension also supports using https://www.vaultproject.io/docs/secrets/databases/index.html[dynamic database credentials]
through the `database-credentials-role` property on the `credentials-provider`. The Vault setup is more
involved and goes beyond the scope of that quickstart guide.
====


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]