ifdef::context[:parent-context: {context}]
[id="knative_{context}"]
= Knative
:context: knative

To enable the generation of Quarkus.Knative.resources, you need to include Knative in the target platforms:

[source]
----
quarkus.kubernetes.deployment-target=knative
----

Following the execution of `./mvnw package` you will notice amongst the other files that are created, two files named
`quarkus.knative.json` and `knative.yml` in the `target/kubernetes/` directory.

If you look at either file you will see that it contains a Quarkus.Knative.`Service`.

The full source of the `quarkus.knative.json` file looks something like this:

[source,json]
----
{
  {
    "apiVersion" : "serving.quarkus.knative.dev/v1alpha1",
    "kind" : "Service",
    "metadata" : {
      "annotations": {
       "app.quarkus.io/vcs-url" : "<some url>",
       "app.quarkus.io/commit-id" : "<some git SHA>"
      },
      "labels" : {
        "app.kubernetes.io/name" : "test-quarkus-app",
        "app.kubernetes.io/version" : "1.0-SNAPSHOT"
      },
      "name" : "quarkus.knative.
    },
    "spec" : {
      "runLatest" : {
        "configuration" : {
          "revisionTemplate" : {
            "spec" : {
              "container" : {
                "image" : "dev.local/yourDockerUsername/test-quarkus-app:1.0-SNAPSHOT",
                "imagePullPolicy" : "IfNotPresent"
              }
            }
          }
        }
      }
    }
  }
}
----

The generated service can be customized using the following properties:

.Knative
[table,tablepcwidth="100",rowcount="29",colcount="4"]
|===
| Property | Type | Description | Default Value
| quarkus.knative.name | String |  | ${quarkus.container-image.name}
| quarkus.knative.version | String |  | ${quarkus.container-image.tag}
| quarkus.knative.part-of | String |  | 
| quarkus.knative.init-containers | Map<String, Container> |  | 
| quarkus.knative.labels | Map |  | 
| quarkus.knative.annotations | Map |  | 
| quarkus.knative.env-vars | Map<String, Env> |  | 
| quarkus.knative.working-dir | String |  | 
| quarkus.knative.command | String[] |  | 
| quarkus.knative.arguments | String[] |  | 
| quarkus.knative.replicas | int |  | 1
| quarkus.knative.service-account | String |  | 
| quarkus.knative.host | String |  | 
| quarkus.knative.ports | Map<String, Port> |  | 
| quarkus.knative.service-type | ServiceType |  | ClusterIP
| quarkus.knative.pvc-volumes | Map<String, PersistentVolumeClaimVolume> |  | 
| quarkus.knative.secret-volumes | Map<String, SecretVolume> |  | 
| quarkus.knative.config-map-volumes | Map<String, ConfigMapVolume> |  | 
| quarkus.knative.git-repo-volumes | Map<String, GitRepoVolume> |  | 
| quarkus.knative.aws-elastic-block-store-volumes | Map<String, AwsElasticBlockStoreVolume> |  | 
| quarkus.knative.azure-disk-volumes | Map<String, AzureDiskVolume> |  | 
| quarkus.knative.azure-file-volumes | Map<String, AzureFileVolume> |  | 
| quarkus.knative.mounts | Map<String, Mount> |  | 
| quarkus.knative.image-pull-policy | ImagePullPolicy |  | IfNotPresent
| quarkus.knative.image-pull-secrets | String[] |  | 
| quarkus.knative.liveness-probe | Probe |  | ( see Probe )
| quarkus.knative.readiness-probe | Probe |  | ( see Probe )
| quarkus.knative.sidecars | Map<String, Container> |  | 
|===

include::modules/deprecated-configuration.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]