ifdef::context[:parent-context: {context}]
[id="looks-like-it-works-out-of-the-box_{context}"]
= Looks like it works out of the box?!?
:context: looks-like-it-works-out-of-the-box

If you open the application's configuration file (`src/main/resources/application.properties`), you can see the following line:

[source]
----
org.acme.restclient.CountriesService/mp-rest/url=https://restcountries.eu/rest
----

which configures our REST client to connect to an SSL REST service.

Now let's build the application as a native executable and run the tests:

[source]
----
./mvnw clean install -Pnative
----

And we obtain the following result:

[source]
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----

So, yes, it appears it works out of the box and this guide is pretty useless.

It's not. The magic happens when building the native executable:

[source]
----
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] /opt/graalvm/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar rest-client-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
----

The important elements are these 3 options:

[source]
----
-H:EnableURLProtocols=http,https --enable-all-security-services -H:+JNI
----

They enable the native SSL support for your native executable.

As SSL is de facto the standard nowadays, we decided to enable its support automatically for some of our extensions:

* the Agroal connection pooling extension (`quarkus-agroal`),
* the Amazon DynamoDB extension (`quarkus-amazon-dynamodb`),
* the Hibernate Search Elasticsearch extension (`quarkus-hibernate-search-elasticsearch`),
* the Infinispan Client extension (`quarkus-infinispan-client`).
* the Jaeger extension (`quarkus-jaeger`),
* the JGit extension (`quarkus-jgit`),
* the Keycloak extension (`quarkus-keycloak`),
* the Kubernetes client extension (`quarkus-kubernetes-client`),
* the Mailer extension (`quarkus-mailer`),
* the MongoDB extension (`quarkus-mongodb-client`),
* the Neo4j extension (`quarkus-neo4j`),
* the OAuth2 extension (`quarkus-elytron-security-oauth2`),
* the REST client extension (`quarkus-rest-client`).

As long as you have one of those extensions in your project, the SSL support will be enabled by default.

Now, let's just check the size of our native executable as it will be useful later:

[source]
----
$ ls -lh target/rest-client-1.0-SNAPSHOT-runner
-rwxrwxr-x. 1 gsmet gsmet 34M Feb 22 15:27 target/rest-client-1.0-SNAPSHOT-runner
----


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]