ifdef::context[:parent-context: {context}]
[id="overriding-properties-at-runtime_{context}"]
= Overriding properties at runtime
:context: overriding-properties-at-runtime

Quarkus does much of its configuration and bootstrap at build time.
Most properties will then be read and set during the build time step.
To change them, make sure to repackage your application.

[source,shell]
----
./mvnw clean package
----

Extensions do define _some_ properties as overridable at runtime.
A canonical example is the database URL, username and password which is only known specifically in your target environment.
This is a tradeoff as the more runtime properties are available, the less build time prework Quarkus can do. The list of runtime properties is therefore lean.

You can override these runtime properties with the following mechanisms (in decreasing priority):

[arabic]
. using system properties:
* for a runner jar: `java -Dquarkus.datasource.password=youshallnotpass -jar target/myapp-runner.jar`
* for a native executable: `./target/myapp-runner -Dquarkus.datasource.password=youshallnotpass`
. using environment variables:
* for a runner jar: `export QUARKUS_DATASOURCE_PASSWORD=youshallnotpass ; java -jar target/myapp-runner.jar`
* for a native executable: `export QUARKUS_DATASOURCE_PASSWORD=youshallnotpass ; ./target/myapp-runner`
. using an environment file named `.env` placed in the current working directory containing the line `QUARKUS_DATASOURCE_PASSWORD=youshallnotpass` (for dev mode, this file can be placed in the root of the project, but it is advised to not check it in to version control)
. using a configuration file placed in `$PWD/config/application.properties`
* By placing an `application.properties` file inside a directory named `config` which resides in the directory where the application runs, any runtime properties defined
in that file will override the default configuration. Furthermore any runtime properties added to this file that were not part of the original `application.properties` file
_will also_ be taken into account.
* This works in the same way for runner jar and the native executable

[NOTE,textlabel="Note",name="note"]
====
Environment variables names are following the conversion rules of link:https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#default-configsources[Eclipse MicroProfile]
====

[NOTE,textlabel="Note",name="note"]
====
The `config/application.properties` features is available in development mode as well. To make use of it, `config/application.properties` needs to be placed inside the build tool's output directory (`target` for Maven and `build/classes/java/main` for Gradle).
Keep in mind however that any cleaning operation from the build tool like `mvn clean` or `gradle clean` will remove the `config` directory as well.
====

include::modules/configuration-profiles.adoc[leveloffset=+1]

include::modules/clearing-properties.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]