ifdef::context[:parent-context: {context}]
[id="packaging-and-run-the-application_{context}"]
= Packaging and run the application
:context: packaging-and-run-the-application

The application is packaged using `./mvnw package`.
It produces 2 jar files in `/target`:

* `getting-started-1.0-SNAPSHOT.jar` - containing just the classes and resources of the projects, it's the regular
artifact produced by the Maven build;
* `getting-started-1.0-SNAPSHOT-runner.jar` - being an executable _jar_. Be aware that it's not an _über-jar_ as
the dependencies are copied into the `target/lib` directory.

You can run the application using: `java -jar target/getting-started-1.0-SNAPSHOT-runner.jar`

[NOTE,textlabel="Note",name="note"]
====
The `Class-Path` entry of the `MANIFEST.MF` from the _runner jar_ explicitly lists the jars from the `lib` directory.
So if you want to deploy your application somewhere, you need to copy the _runner_ jar as well as the _lib_ directory.
====

[NOTE,textlabel="Note",name="note"]
====
Before running the application, don't forget to stop the hot reload mode (hit `CTRL+C`), or you will have a port conflict.
====


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]