ifdef::context[:parent-context: {context}]
[id="password-storage-and-hashing_{context}"]
= Password storage and hashing
:context: password-storage-and-hashing

By default, we consider passwords to be stored hashed with https://en.wikipedia.org/wiki/Bcrypt[bcrypt] under the
https://en.wikipedia.org/wiki/Crypt_(C)[Modular Crypt Format] (MCF).

When you need to create such a hashed password we provide the convenient `String BcryptUtil.bcryptHash(String password)`
function, which defaults to creating a random salt and hashing in 10 iterations (though you can specify the iterations and salt
too).

[NOTE,textlabel="Note",name="note"]
====
with MCF you don't need dedicated columns to store the hashing algo, the iterations count or the salt because
they're all stored in the hashed value.
====

WARN: you can also store passwords in clear text with `@Password(PasswordType.CLEAR)` but we strongly recommend against
it in production.


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]