ifdef::context[:parent-context: {context}]
[id="quarkus_{context}"]
= Quarkus Integration
:context: quarkus

If you want to use Qute in your Quarkus application add the following dependency to your project:

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-qute</artifactId>
</dependency>
----

In Quarkus, a preconfigured engine instance is provided and available for injection - a bean with scope `@Singleton`, bean type `io.quarkus.qute.Engine` and qualifier `@Default` is registered automatically.
Moreover, all templates located in the `src/main/resources/templates` directory are validated and can be easily injected.

[source,java]
----
import io.quarkus.qute.Engine;
import io.quarkus.qute.Template;
import io.quarkus.qute.api.ResourcePath;

class MyBean {

    @Inject
    Template items; <1>

    @ResourcePath("detail/items2_v1.html") <2>
    Template items2;

    @Inject
    Engine engine; <3>
}
----

[arabic]
<1> If there is no `ResourcePath` qualifier provided, the field name is used to locate the template. In this particular case, the container will attempt to locate a template with path `src/main/resources/templates/items.html`.
<2> The `ResourcePath` qualifier instructs the container to inject a template from a path relative from `src/main/resources/templates`. In this case, the full path is `src/main/resources/templates/detail/items2_v1.html`.
<3> Inject the configured `Engine` instance.

include::modules/injecting-beans-directly-in-templates.adoc[leveloffset=+1]

include::modules/parameter.adoc[leveloffset=+1]

include::modules/template.adoc[leveloffset=+1]

include::modules/template.adoc[leveloffset=+1]

include::modules/resteasy-integration.adoc[leveloffset=+1]

include::modules/development-mode.adoc[leveloffset=+1]

include::modules/configuration-reference.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]