ifdef::context[:parent-context: {context}]
[id="the-truststore-path_{context}"]
= The TrustStore path
:context: the-truststore-path

You haven't noticed anything but, while building the image,
Quarkus has automatically set `javax.net.ssl.trustStore` to point to the `cacerts` file bundled in the GraalVM distribution.
This file contains the root certificates.

This is useful when running tests but, obviously, it is not portable as this path is hardcoded.

You can check that pretty easily:

* move your GraalVM directory to another place (let's call it `<new-graalvm-home>`)
* run the native executable `./target/rest-client-1.0-SNAPSHOT-runner`
* in a browser, go to `http://localhost:8080/country/name/greece`
* you will have an Internal Server Error
* in your terminal, you should have an exception: `java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`
* hit `Ctrl+C` to stop the application

To make it work, you need to manually set `javax.net.ssl.trustStore` to point to the new GraalVM home:

[source]
----
./target/rest-client-1.0-SNAPSHOT-runner -Djavax.net.ssl.trustStore=<new-graalvm-home>/jre/lib/security/cacerts
----

Now, the application should work as expected:

* in a browser, go to `http://localhost:8080/country/name/greece`
* you should see a JSON output with some information about Greece
* hit `Ctrl+C` to stop the application

[TIP,textlabel="Tip",name="tip"]
====
The root certificates file of GraalVM might not be totally up to date.
If you have issues with some certificates, your best bet is to include the `cacerts` file of a regular JDK instead.
====

[WARNING,textlabel="Warning",name="warning"]
====
Don't forget to move your GraalVM directory back to where it was.
====

include::modules/working-with-containers.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]