[id="configuring-the-application_{context}"]
= Configuring the Application

The `elytron-security-jdbc` extension requires at least one datasource to access to your database.

[source,properties]
----
quarkus.datasource.url=jdbc:postgresql:elytron-security-jdbc
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
----

In our context, we are using PostgreSQL as identity store and we init the database with users and roles.

[source,sql]
----
CREATE TABLE test_user (
  id INT,
  username VARCHAR(255),
  password VARCHAR(255),
  role VARCHAR(255)
);

INSERT INTO test_user (id, username, password, role) VALUES (1, 'admin', 'admin', 'admin');
INSERT INTO test_user (id, username, password, role) VALUES (2, 'user','user', 'user');
----

[NOTE,textlabel="Note",name="note"]
====
It is probably useless but we kindly remind you that you must not store clear-text passwords in production environment ;-).
The `elytron-security-jdbc` offers a built-in bcrypt password mapper.
====

We can now configure the Elytron JDBC Realm.

[source,properties]
----
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password, u.role FROM test_user u WHERE u.username=? <1>
quarkus.security.jdbc.principal-query.clear-password-mapper.enabled=true <2>
quarkus.security.jdbc.principal-query.clear-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=2 <3>
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups
----
The `elytron-security-jdbc` extension requires at least one principal query to autenticate the user and its identity.

[arabic]
<1> We define a parameterized SQL statement (with exactly 1 parameter) which should return the user's password plus any additional information you want to load.
<2> We  configure the password mapper with the position of the password field in the `SELECT` fields and other information like salt, hash encoding, etc.
<3> We use `attribute-mappings` to bind the `SELECT` projection fields (ie. `u.role` here) to the target Principal representation attributes.
[NOTE,textlabel="Note",name="note"]
====
In the `principal-query` configuration all the `index` properties start at 1 (rather than 0).
====