[id="prepared-queries_{context}"]
= Prepared queries

The Reactive PostgreSQL Client can also prepare queries and take parameters that are replaced in the SQL statement at execution time:

[source,java]
----
client.preparedQuery("SELECT name FROM fruits WHERE id = $1", Tuple.of(id))
----

[TIP,textlabel="Tip",name="tip"]
====
The SQL string can refer to parameters by position, using $1, $2, ...etc.
====

Like the simple `query` method, `preparedQuery` returns an instance of `Uni<RowSet>`.
Equipped with this tooling, we are able to safely use an `id` provided by the user to get the details of a particular fruit:

.src/main/java/org/acme/vertx/Fruit.java
[source,java]
----
public static Uni<Fruit> findById(PgPool client, Long id) {
    return client.preparedQuery("SELECT id, name FROM fruits WHERE id = $1", Tuple.of(id)) // <1>
            .map(RowSet::iterator) // <2>
            .map(iterator -> iterator.hasNext() ? from(iterator.next()) : null); // <3>
}
----
[arabic]
<1> Create a `Tuple` to hold the prepared query parameters.
<2> Get an `Iterator` for the `RowSet` result.
<3> Create a `Fruit` instance from the `Row` if an entity was found.
And in the JAX-RS resource:

.src/main/java/org/acme/vertx/FruitResource.java
[source,java]
----
@GET
@Path("{id}")
public Uni<Response> getSingle(@PathParam Long id) {
    return Fruit.findById(client, id)
            .map(fruit -> fruit != null ? Response.ok(fruit) : Response.status(Status.NOT_FOUND)) // <1>
            .map(ResponseBuilder::build); // <2>
}
----
[arabic]
<1> Prepare a JAX-RS response with  either the `Fruit` instance if found or the `404` status code.
<2> Build and send the response.
The same logic applies when saving a `Fruit`:

.src/main/java/org/acme/vertx/Fruit.java
[source,java]
----
public Uni<Long> save(PgPool client) {
    return client.preparedQuery("INSERT INTO fruits (name) VALUES ($1) RETURNING (id)", Tuple.of(name))
            .map(pgRowSet -> pgRowSet.iterator().next().getLong("id"));
}
----

And in the web resource we handle the `POST` request:

.src/main/java/org/acme/vertx/FruitResource.java
[source,java]
----
@POST
public Uni<Response> create(Fruit fruit) {
    return fruit.save(client)
            .map(id -> URI.create("/fruits/" + id))
            .map(uri -> Response.created(uri).build());
}
----