name: Quarkus Kubernetes Test

on: workflow_dispatch

env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: "Prepare release"
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus'
    env:
      MAVEN_OPTS: -Xmx2048m -XX:MaxMetaspaceSize=1000m
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Set up JDK 8
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: 8
      - name: Create maven repo
        run: mkdir -p $HOME/release/repository
      - name: Build and Test
        run: |
          mvn --settings .github/mvn-settings.xml \
            -B \
            -DskipITs -Dinvoker.skip=true \
            -Dmaven.repo.local=$HOME/release/repository \
            clean install
      - name: OpenShift Tests
        run: |
            echo mock publish somewhere to kubernetes